package nve:wasm-component;

interface host {
  log: func(message: string);
}

world wasm-component {
  import host;

  export name: func() -> string;
  export process: func(a: s32, b: s32) -> s32;
}
